<?php include __DIR__ . '/header.phtml'; ?>

<main>
    
    <div class="d-flex justify-content-center align-items-center flex-grow-1">
        <div class="mt-5 px-4 py-4 shadow-lg">
            <h2 class="page-title text-center">Inscription</h2>
            <form id="inscriptionForm" method="POST" action="inscription-form.php">
                <div class="mb-3">
                    <label for="PseudoInput" class="form-label">Pseudo</label>
                    <input type="text" class="form-control" id="PseudoInput" placeholder="Votre pseudo" name="Pseudo">
                    <div class="invalid-feedback">
                    Pseudo manquant
                    </div>
                    <div class="valid-feedback">
                        Pseudo valide
                    </div> 
                </div>
                <div class="mb-3">
                    <label for="EmailInput" class="form-label">Email</label>
                    <input type="email" class="form-control" id="EmailInput" placeholder="adresse@mail.fr" name="Email"> 
                    <div class="invalid-feedback">
                    Le mail n'est pas au bon format
                    </div>
                    <div class="valid-feedback">
                    Le mail est au bon format
                    </div>
                </div>
                <div class="mb-3">
                    <label for="PasswordInput" class="form-label">Mot de passe</label>
                    <input type="password" class="form-control" id="PasswordInput" name="Password">
                    <div class="invalid-feedback">
                        Mot de passe pas assez robuste : au moins 8 caractères, comprenant au moins 1 lettre majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial
                    </div>
                    <div class="valid-feedback">
                        Mot de passe robuste
                    </div>
                </div>
                <div class="mb-3">
                    <label for="ValidatePasswordInput" class="form-label">Confirmer votre mot de passe</label>
                    <input type="password" class="form-control" id="ValidatePasswordInput" name="PasswordConfirm">
                    <div class="invalid-feedback">
                        La confirmation n'est pas identique au mot de passe
                    </div>
                    <div class="valid-feedback">
                        La confirmation du mot de passe est identique
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-inscription" id="ValidateSign">Inscription</button>
                </div>
            </form>
            <div class="text-center pt-3">
                <p>Vous avez déjà un compte ? <a class="form-link" href="connexion.php">Connectez-vous ici !</a></p>
            </div>
        </div>
    </div>    
</main>

<?php include __DIR__ . '/footer.phtml'; ?>