<?php include __DIR__ . '/header.phtml'; ?>

<main>
   
    <div class="d-flex justify-content-center align-items-center flex-grow-1">
        <div class="mt-5 px-5 py-5 shadow-lg">
            <h2 class="page-title mb-5 text-center"><i class="bi bi-envelope-paper"></i> Nous Contacter</h2>
            <form id="contactForm" method="POST" action="contact-form.php">
                 <div class="mb-3">
                    <label for="NomInput" class="form-label">Votre Nom</label>
                    <input type="text" class="form-control" id="NomInput" placeholder="Pierre Dupont" name="Nom">
                    <div class="invalid-feedback">
                    Nom manquant
                    </div>
                    <div class="valid-feedback">
                        Nom valide
                    </div> 
                </div>
                <div class="mb-3">
                    <label for="EmailInput" class="form-label">Votre Email</label>
                    <input type="email" class="form-control" id="EmailInput" placeholder="adresse@mail.fr" name="Email"> 
                    <div class="invalid-feedback">
                    Le mail n'est pas au bon format
                    </div>
                    <div class="valid-feedback">
                    Le mail est au bon format
                    </div>
                </div>
                <div class="mb-3">
                    <label for="MessageInput" class="form-label">Votre Message</label>
                    <textarea class="form-control" id="MessageInput" name="subject" placeholder="Écrivez votre message ici..."></textarea>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-envoyer">Envoyer</button>
                </div>
            </form>
        </div>
    </div>

</main>

<?php include __DIR__ . '/footer.phtml'; ?>