<!DOCTYPE html>
<html class="h-100" lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EcoRide</title>
    <link rel="stylesheet" href="css/main.min.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script defer src="js/signUp.js"></script>
</head>
<body class="min-vw-100 h-100 d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-lg navbar-custom py-3">
            <div class="container-fluid px-4">
                <!-- Logo + brand texte -->
                <a class="navbar-brand d-flex align-items-center" href="#">
                    <img src="img/logo-ecoride.png" alt="EcoRide Logo" class="logo-img">
                    <span class="brand-text ms-2">EcoRide</span>
                </a>

                <!-- Bouton pour menu mobile -->
                <button class="navbar-toggler border-0" type="button" 
                    data-bs-toggle="collapse" data-bs-target="#navbarContent" 
                    aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Liens et boutons -->
                <div class="collapse navbar-collapse" id="navbarContent">
                    
                    <div class="navbar-nav mx-auto">
                        <a class="nav-link" href="index.php">Accueil</a>
                        <a class="nav-link" href="covoiturages.php">Covoiturages</a>
                        <a class="nav-link" href="contact.php">Contact</a>
                    </div>

                    <!-- Boutons Connexion / Inscription à droite -->
                    <div class="d-flex align-items-center me">
                        <a href="connexion.php" class="btn btn-outline-light me-2">Connexion</a>
                        <a href="inscription.php" class="btn btn-light">Inscription</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>